apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: wordpress
      app.kubernetes.io/component: wordpress
      app.kubernetes.io/instance: wordpress
    name: wordpress
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: quay.io/ericbos1/wordpress:5.3.0
      from:
        kind: DockerImage
        name: quay.io/ericbos1/wordpress:5.3.0
      generation: null
      importPolicy:
        importMode: Legacy
      name: 5.3.0
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"wordpress:5.3.0"},"fieldPath":"spec.template.spec.containers[?(@.name==\"wordpress\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: wordpress
      app.kubernetes.io/component: wordpress
      app.kubernetes.io/instance: wordpress
    name: wordpress
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: wordpress
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: wordpress
      spec:
        containers:
        - image: ' '
          name: wordpress
          env:
          - name: WORDPRESS_DB_HOST
            value: mysql
          - name: WORDPRESS_DB_NAME
            value: wordpress
          - name: WORDPRESS_DB_user
            valueFrom:
              secretKeyRef:
                name: wp-secret
                key: user
          - name: WORDPRESS_DB_password
            valueFrom:
              secretKeyRef:
                name: wp-secret
                key: password
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          volumeMounts:
          - mountPath: /var/www/html
            name: wordpress-volume-1
        volumes:
        - emptyDir: {}
          name: wordpress-volume-1
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: wordpress
      app.kubernetes.io/component: wordpress
      app.kubernetes.io/instance: wordpress
    name: wordpress
  spec:
    ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      deployment: wordpress
  status:
    loadBalancer: {}
kind: List
metadata: {}
